version: "3"
services:
  ################################
  #   Setup React-admin container
  ################################
  frontend:
    build: 
      context: ./frontendN
      dockerfile: Dockerfile.dev
    environment:
      - REACT_APP_NODE_ENV=${REACT_APP_NODE_ENV}
      - REACT_APP_HOST_GRAPHAL=${REACT_APP_HOST_GRAPHAL}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - PORT=${FRONTEND_PORT}
    ports:
      - "3000:3000"
    volumes:
      - ./frontendN/src:/app/src
      - ./uploads:/var/storage
    networks:
      - nodejs
  ################################
  
  ################################
  #   Setup Api Graphql container
  ################################
  graphql:
    build: 
      context: ./graphqlN
      dockerfile: Dockerfile.dev                
    ports:
      - "4000:4000"
    volumes:
      - ./graphqlN/src:/app/src        
      - ./uploads:/app/uploads    
    environment:
      - RA_HOST=${RA_HOST}
      - GRAPHQL_PORT=${GRAPHQL_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=mongodb://${MONGO_INITDB_USERNAME}:${MONGO_INITDB_PASSWORD}@mongo:${MONGO_PORT}/${MONGO_INITDB_DATABASE}?authMechanism=DEFAULT
    networks:
      - nodejs
  ################################

  ################################
  #   Setup Api Mongo and mongo-express container
  ################################
  mongo:
    container_name: mongo
    image: mongo:${MONGO_VERSION}
    command: mongod --port ${MONGO_PORT}
    expose:
      - ${MONGO_PORT}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - ./mongo-single/data:/data/db
      - ./mongo-single/restore:/mongo-single/restore
      - ./mongo-single/mongod.conf:/etc/mongod.conf
    restart: always
    networks:
      - nodejs

networks:
  nodejs:
    external: true 
    name: banlist-network