version: "3"
services:
  ################################
  #   Setup React-admin container
  ################################
  frontend:
    build: 
      context: ./frontendN
      dockerfile: Dockerfile.prod
      args:
        REACT_APP_HOST_GRAPHAL: ${REACT_APP_HOST_GRAPHAL} 
        REACT_APP_NODE_ENV: ${REACT_APP_NODE_ENV} 
        REACT_APP_GOOGLE_CLIENT_ID: ${REACT_APP_GOOGLE_CLIENT_ID} 
        REACT_APP_FACEBOOK_APPID: ${REACT_APP_FACEBOOK_APPID} 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontendN/src:/app/src
      - ./uploads:/var/storage
    networks:
      - nodejs
  ################################

  ################################
  #   Setup Api Graphql container
  ################################
  
  graphql:
    build: 
      context: ./graphqlN
      dockerfile: Dockerfile.prod   
      # args:
      #   RA_HOST: ${RA_HOST}
      #   GRAPHQL_PORT: ${GRAPHQL_PORT}
      #   JWT_SECRET: ${JWT_SECRET}
    ports:
      - "4000:4000"
    volumes:
      - ./uploads:/app/uploads  
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_USERNAME}:${MONGO_INITDB_PASSWORD}@mongo:27017/${MONGO_INITDB_DATABASE}?authMechanism=DEFAULT
      - RA_HOST: ${RA_HOST}
      - GRAPHQL_PORT: ${GRAPHQL_PORT}
      - JWT_SECRET: ${JWT_SECRET}
    networks:
      - nodejs
  ################################

  ################################
  #   Setup Api Mongo and mongo-express container
  ################################
  mongo:
    image: mongo:${MONGOD_VERSION}
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-single/data:/data/db
      - ./mongo-single/restore:/mongo-single/restore
      - ./mongo-single/mongod.conf:/etc/mongod.conf
    restart: always
    networks:
      - nodejs
networks:
  nodejs:
    external: true 
    name: banlist-network
