# stage: 1
FROM node:12
WORKDIR /app
COPY . /app
# RUN npm install 

# RUN rm -rf node_modules

RUN npm i --save --legacy-peer-deps

RUN npm install -g nodemon
RUN npm install -g ts-node


# RUN mkdir -p /app/src/upload
# RUN chmod -R 777 /app/src/upload

# RUN npm run build

# CMD ["node", "index.js"]
# CMD [ "npm", "start" ]
CMD [ "npm", "run", "dev" ]