version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=true
      - node.name=node-1
    # volumes:
    #   - ./elasticsearch-data:/usr/share/elasticsearch/data
    volumes:
      - ./elasticsearch-data:/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    # networks: ['stack']
    networks:
      - elasticsearch-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    ports: ['5601:5601']
    # networks: ['stack']
    links: ['elasticsearch']
    depends_on: ['elasticsearch']
    networks:
      - elasticsearch-network

networks:
  elasticsearch-network:
    external:
      name: banlist-network
  
